# The frontend is the only part of the website stack that is exposed.

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: website
  name: dep-frontend
spec:
  selector:
    matchLabels:
      app: pod-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-frontend
        infrastructure: fargate
    spec:
      containers:
      - name: container-frontend
        image: forsakenidol/frontend
        imagePullPolicy: Always
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: cronmap
              key: server_hostname
        - name: SERVER_PORT
          value: "9001"
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  namespace: website
  name: frontend-service
spec:
  selector:
    app: pod-frontend
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: website
  name: frontend-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # SSL (HTTPS)
#    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-2:881197861415:certificate/cacb5ebd-89ab-4864-ac19-bdb39499be8f
    # SSL (HTTPS) (Isengard Certificate)
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-2:908684752359:certificate/b529b928-c6e6-4969-8c58-5bda99db6abe
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/tags: auto-delete=no
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-service
              port:
                number: 9002
--- 