apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: website
  name: github-cronjob
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            infrastructure: fargate
        spec:
          containers:
          - name: github-container
            image: forsakenidol/cronjob
            imagePullPolicy: IfNotPresent
            env:
            - name: GITHUB_PAN
              valueFrom:
                secretKeyRef:
                  name: cronjob-credentials
                  key: GITHUB_PAN
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  # The name of the ConfigMap containing the value you want to assign
                  name: cronmap
                  # Specify the key associated with the value
                  key: server_hostname
          restartPolicy: OnFailure