---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: postgres
  name: dep-postgres
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pod-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pod-postgres
    spec:
      containers:
      - name: container-postgres
        image: postgres:14.3
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD
          value: "xdlmaotrash"
        ports:
          - containerPort: 5432
            name: postgres-port
---
apiVersion: v1
kind: Service
metadata:
  namespace: postgres
  name: service-postgres
spec:
  selector:
    app.kubernetes.io/name: pod-postgres
  ports:
    - name: postgres-svc-port
      port: 5432
      targetPort: 5432
      protocol: TCP
---